### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-http-driver#10]
It's not complicated to extend HTTP Driver to have cache. A request object can have an option for time-to-live, then when the driver receives the request object, it keeps the response and the respective request in a Map. When a new request comes in it is checked against that Map. Alternatively, the request object can have an option `fresh` which always ignores cache.

**Comment by teohhanhui** [comment]
Shouldn't caching be the responsibility of the HTTP layer? (Though of course, this is not an ideal world...)

**Comment by staltz** [comment]
We can either put caching as a driver configuration on the factory, or a configuration on the request. Or both. I need to investigate.

**Comment by teohhanhui** [comment]
I was thinking of HTTP caching http://tools.ietf.org/html/rfc7234

**Comment by staltz** [comment]
Yes, if you have that, great.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#234
