### ISSUE TITLE
More control over superagent

### ISSUE THREAD

**Issue by teohhanhui** [cyclejs/cycle-http-driver#15]
e.g.
```js
import superagent from 'superagent';
// monkeypatch
superagent.parse['application/ld+json'] = superagent.parse['application/json'];
```
```js
request.parse(fn)
```
```js
request.use(fn)
```

Thoughts?

**Comment by teohhanhui** [comment]
These are undocumented because docs for superagent just plain sucks...

**Comment by Cmdv** [comment]
@staltz can you assign me to this please?

**Comment by staltz** [comment]
Assigning isn't really a proper open source community feature in Github, it's meant for people in organizations, so let's just go with the label "in progress". What matters most is that you told in this issue that you're working on it, so other people don't do duplicate work. :)

**Comment by Cmdv** [comment]
cool will do it like that. Thanks :)

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#236
