### ISSUE TITLE
Doesn't work with custom elements?

### ISSUE THREAD

**Issue by YourDeveloperFriend** [cyclejs/cycle-http-driver#22]
I'm not sure where things are at, but when I tried to use this driver in a custom element, it kept throwing errors on me. On the input side, it didn't recognize the `HTTP` field on the requests object, and on the output side, when I tried to emit a url to fetch, cycle core threw an error saying it couldn't validate the response object.

**Comment by Frikki** [comment]
Please provide the following:
- an overview with the stack trace of the error being thrown,
- why you believe it’s a bug,
- versions of cycle-core and cycle-http-driver
- whether it’s a problem in all browsers or a specific,
- unambiguous set of steps to reproduce the error
- any related issues, and
- what you think might cause the error if you can.

**Comment by staltz** [comment]
@YourDeveloperFriend Cycle DOM Custom elements are meant to implement UI 'widgets' only, for this reason they don't support any other driver than the DOM driver. This is just like React components for example (where you override `render` of the class, but there is no such thing as `renderHTTPRequest` to be overriden, any HTTP logic added to a component is ad-hoc).

**Comment by YourDeveloperFriend** [comment]
Thanks for the help!

> This is just like React components for example

Not quite. React advertises itself as a View only, so it doesn't concern itself with how network requests are made. Cyclejs, on the other hand, uses drivers to interact with the network. If only the `main` component can make network requests (or interact with any driver), then it makes it difficult to build large applications, filling the one main file with lots of bloat and separating functionality from the components that depend on that data.

> Also, we are working on deprecating custom elements, to favor Nested Dialogues instead.

Seems a shame, looking at your example, there's a lot of boilerplate involved with hooking things up. Maybe if you provided some utility functions to ease the burden? It seems like there's a lot of danger in parent component's needing to know specific details about the implementation of the child component.

Anyways, just my two cents, I wish you luck, I'm excited to see how this project progresses.

**Comment by staltz** [comment]
> Not quite. React advertises itself as a View only, so it doesn't concern itself with how network requests are made.

And Cycle DOM is "the View only". Custom elements are an artifact of Cycle DOM.

> Cyclejs, on the other hand, uses drivers to interact with the network. If only the main component can make network requests (or interact with any driver), then it makes it difficult to build large applications, filling the one main file with lots of bloat and separating functionality from the components that depend on that data.

This actually isn't different to Flux, where (nowadays) there is only one store, and actions are events passed through a global Dispatcher (like an Event Bus). Notice how in Flux+React, React components do not have any network request logic, these need to be handled "globally" by Flux.

These problems are why we came up with nested dialogues architecture, where for instance each "component" handles its own HTTP logic, styles, etc. The best example of this is https://github.com/futurice/power-ui/tree/master/src, I recommend checking it carefully before we have official docs on this new approach. Basically, nested dialogues are a natural way of being able to export not just `DOM` and `events` from your "custom element", but also HTTP and whatever else you wish. It's pretty much what you are asking for in this issue. Here's a specific example: https://github.com/futurice/power-ui/blob/master/src/components/pages/PowerheadPage/index.js#L42-L47 .

> Seems a shame, looking at your example, there's a lot of boilerplate involved with hooking things up. Maybe if you provided some utility functions to ease the burden? It seems like there's a lot of danger in parent component's needing to know specific details about the implementation of the child component.

What boilerplate and what "parent needing to know details about child" are you talking about? I can't recognize. The latter should definitely not exist. The whole point of this architecture is to avoid the latter as much as possible.

**Comment by YourDeveloperFriend** [comment]
I'm still learning about these new techniques with Observables, so forgive me as I pick your brain :D.

> These problems are why we came up with nested dialogues architecture.

Awesome, I'm glad to see that I'm not the only one who recognized the problem with custom widget components not having access to the HTTP (or other) drivers. Thanks for bringing that to my attention.

> What boilerplate and what "parent needing to know details about child" are you talking about?

[This line](https://github.com/cyclejs/todomvc-cycle/blob/master/src/components/todos/index.js#L19), in the example on the blog post, is where I see the problem. Three problems:

1) If you have a component nested five components deep, for example, and then find you have a need for a driver (like, for example, HTTP or local storage), then you'd have to modify the five files to get that component access.
2) It seems a bit odd that the declaration of the child component takes place in the parent component's intent.
3) Composing elements together creates a problem with the jquery events.

I understand that these are hard problems to address (React is still trying to figure out problem 1 with `context` and global singletons), but I really liked the way you had things laid out with the custom elements, similar to react. It made sense to me that each component would have direct access to the drivers, and the only parent-child interaction came through props and events. I understand if you disagree.

More on problem 3 - With the current custom elements architecture, you could integrate into cyclejs some way to prevent the jquery-like selectors from pulling events from elements in other, unrelated components. With the new architecture, all that has to be done manually.

**Comment by staltz** [comment]
> More on problem 3 - With the current custom elements architecture, you could integrate into cyclejs some way to prevent the jquery-like selectors from pulling events from elements in other, unrelated components. With the new architecture, all that has to be done manually.

We're working on that a lot. Basically it's conceptually solved, we just need to build the final bits and document it. See this https://github.com/cyclejs/cycle-core/issues/167 and these branches https://github.com/cyclejs/cycle-dom/tree/auto-scope

**Comment by YourDeveloperFriend** [comment]
Awesome, thanks for all the hard work!

**Comment by Frikki** [comment]
@YourDeveloperFriend 
> 1) If you have a component nested five components deep, for example, and then find you have a need for a driver (like, for example, HTTP or local storage), then you'd have to modify the five files to get that component access.

You actually don’t. You have all the drivers available in your `main()` through sources. Now all you need to do is pass these sources to components. If a new source is added, it will simply be available down the chain, and the component that needs it, simply has to access it in its declaration.

> 2) It seems a bit odd that the declaration of the child component takes place in the parent component's intent.

It really shouldn’t. Most of the time, your components should be declared in a rather flat file structure, I think. It can, though, at times, make sense to arrange them in groups or hierarchies. A component is function, and so you call it wherever you need it, e.g., in another component.
