### ISSUE TITLE
tighter coupling for requests and response handlers

### ISSUE THREAD

**Issue by edge** [cyclejs/cycle-http-driver#26]
I can't help but feel that using https://github.com/cyclejs/cycle-http-driver/blob/master/examples/search/search.js#L6 and https://github.com/cyclejs/cycle-http-driver/blob/master/examples/search/search.js#L15 isn't very maintainable.

Currently, responses aren't provided with any concrete relationship to their requests, so instead we rely on string parsing, which is an unnecessary overhead and layer of indirection.

It also poses potential conflicts for similar URIs and hierarchical resources.

Is there a way to more tightly couple responses to their requests so that we can avoid this problem?

**Comment by edge** [comment]
One way about this is to create an abstraction object with the request URI and a unique ID. This way, the ID can be checked on the way back in and delegated to the correct response handler.

**Comment by staltz** [comment]
Something similar to your last comment, you can attach an id to the request object, then check if `res$.request.id` matches the id you expect.

**Comment by whitecolor** [comment]
@edge #41 this PR also adds orical request object to each particular response.

**Comment by staltz** [comment]
I'll close this issue. If the discussion revives, we can reopen.
