### ISSUE TITLE
examples are broken

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-http-driver#32]
the `search` and `hello-world` examples are broken because they filter the source stream via `sources.HTTP.filter(res$ => res$.request === HELLO_URL)` and rely on `res$.request` being an URL string.

In reality `res$.request` is an object `{url, eager}`:
https://github.com/cyclejs/cycle-http-driver/blob/master/src/http-driver.js#L130-L135

**Comment by staltz** [comment]
Correct
