### ISSUE TITLE
Prefix (base) URL option

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cycle-http-driver#35]
Often apps are desined to make remote cross domain requests using standard ajax, for example packed mobile web apps (i.e phonegap), so to every request its needed to have a host. 

So that on the web it will make requests to:
```
GET /api/something
```

And actually the same app packed should make requests

```
GET http://myhost.domain/api/something
```

And usually this is required for *all http* requests in the app.

Not sure if the propsal lays within the driver concept, but it would be convinient not to append this prefix URL to each request in the code or making some wrapper arround it.

Superagent has prefix module for that, but I think http-driver may abstract it.
https://github.com/johntron/superagent-prefix

**Comment by staltz** [comment]
I'll mark this idea as a potential new feature without breaking changes. Not a priority, so I'll build it when I have time, unless we get a PR. 

Thanks.

**Comment by whitecolor** [comment]
@staltz how would you call the option prop:
1) "prefix"
2) "prefixURL"
3) "baseURL"
..
?

**Comment by staltz** [comment]
http://www.gilliganondata.com/index.php/2012/05/22/the-anatomy-of-a-url-protocol-hostname-path-and-parameters/

Two options:
`protocol`
`hostname`

**Comment by whitecolor** [comment]
Potentially there can be also aditional `path` prefix.

**Comment by whitecolor** [comment]
I would simplify to just "prefix". Why split?

**Comment by staltz** [comment]
Well, ok.

**Comment by whitecolor** [comment]
Can not run tests on Windows machine normaly need to hack a lot. BTW do you plan to move to babel 6 here?

**Comment by whitecolor** [comment]
@staltz added this https://github.com/cyclejs/cycle-http-driver/pull/37

```
"precompile-lib": "rm -rf lib/ && mkdir -p lib",
```
 -p  option is not needed here and it is not supported on windows.

**Comment by whitecolor** [comment]
Create new one  https://github.com/cyclejs/cycle-http-driver/pull/38

**Comment by whitecolor** [comment]
Closing.
