### ISSUE TITLE
dependecy on emiiter and reduce

### ISSUE THREAD

**Issue by mamciek** [cyclejs/cycle-http-driver#43]
I cannot load http-driver because it tries to load emitter.js and reduce.js . Shouldn't them be declared as dependencies?

var Emitter = require('emitter');
var reduce = require('reduce');

**Comment by mamciek** [comment]
I am also having problem with 
`var Rx = (typeof window !== "undefined" ? window['Rx'] : typeof global !== "undefined" ? global['Rx'] : null);`

Why isn't rx loaded with `require('rx')` ?

**Comment by TylorS** [comment]
I don't have any idea where you're getting `emitter.js` or `reduce.js` from, but Rx is a peer dependency. It's expected to be loaded from a separate file like : `https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.0.6/rx.all.js`

**Comment by TrippBlunschi** [comment]
I get the same error when loading with jspm.

`"jspm": {
    "name": "tricycle",
    "dependencies": {
      "@cycle/core": "npm:@cycle/core@6.0.2",
      "@cycle/dom": "npm:@cycle/dom@9.0.2",
      "@cycle/http": "npm:@cycle/http@8.0.0",
      "rx": "npm:rx@^4.0.7"
    },
...`

**Comment by TrippBlunschi** [comment]
I get the same error when trying to load with jspm.

`"jspm": {
    "name": "tricycle",
    "dependencies": {
      "@cycle/core": "npm:@cycle/core@6.0.2",
      "@cycle/dom": "npm:@cycle/dom@9.0.2",
      "@cycle/http": "npm:@cycle/http@8.0.0",
      "rx": "npm:rx@^4.0.7"
    },`

**Comment by TrippBlunschi** [comment]
Adding the cdn to rx.all.js solves the problem, but that shouldn't be necessary, correct? In my case, JSPM loads rx as a peer dependency.

**Comment by staltz** [comment]
I don't use JSPM. Can you submit a PR to fix this for your use case?

**Comment by jamesgorrie** [comment]
If you require `Rx` into the file it should work, as @TylorS mentioned, `Rx` it's expected to be loaded.

e.g.
__Doesn't work__
```JS
import Cycle from '@cycle/core';
import CycleHTTPDriver from '@cycle/http';
```

__Does work__
```JS
import Rx from 'rx';
import Cycle from '@cycle/core';
import CycleHTTPDriver from '@cycle/http';
```

**Comment by jamesgorrie** [comment]
Annoyingly, what I said above is incorrect. Once you try to reference `CycleHTTPDriver` it throws the same errors.

If you however make `JSPM` reference the `lib/http-driver` - we're all good. I'm trying to figure out why and what the best solution for this would be in the long run though.
