### ISSUE TITLE
Observable does not send onComplete notification on request's response?

### ISSUE THREAD

**Issue by apostiglioni** [cyclejs/cycle-http-driver#44]
I would expect that the piece of code below displays something in the console. However, nothing happens:

```
const pictures$ = drivers.HTTP
    .filter(res$ => res$.request.url === HELLO_URL)
    .mergeAll()  //Required to merge all the request data
    .reduce((acc, res) => [...acc].concat(JSON.parse(res.text)), [])
    .flatMap(e=>e)
    .groupBy(function(o) { return o.date})
    .flatMap(function(e) { return e.toArray()})
    .reduce((acc, e) => [...acc, e], [])
    .subscribe(e => { console.log(e) })
```

On the other hand, if I replace the HTTP driver for an array observable, it works as expected:

```
const pictures$ = Observable.just({text:`[
    { "src": "http://dummyimage.com/3000x2000/aaa/fff", "thumb": "http://dummyimage.com/600x400/aaa/fff", "w": 3000, "h": 2000, "date": "2016-01-01" },
    { "src": "http://dummyimage.com/3000x2000/aaa/fff", "thumb": "http://dummyimage.com/600x400/aa0/fff", "w": 3000, "h": 2000, "date": "2016-01-01" },
    { "src": "http://dummyimage.com/3000x2000/aaa/fff", "thumb": "http://dummyimage.com/600x400/2aa/fff", "w": 3000, "h": 2000, "date": "2016-01-02" },
    { "src": "http://dummyimage.com/3000x2000/aaa/fff", "thumb": "http://dummyimage.com/600x400/2ae/fff", "w": 3000, "h": 2000, "date": "2016-01-02" }
]`})
    .reduce((acc, res) => [...acc].concat(JSON.parse(res.text)), [])
    .flatMap(e=>e)
    .groupBy(function(o) { return o.date})
    .flatMap(function(e) { return e.toArray()})
    .reduce((acc, e) => [...acc, e], [])
    .subscribe(e => { console.log(e) })
```

**Comment by laszlokorte** [comment]
your are subscribing to flattened `request` stream.
Each `response` stream on it's own completes but the `request` stream does not complete because there could always be another request. (depending on how you create your `request` sink stream)

**Comment by staltz** [comment]
You probably want to use `scan` instead of `reduce`.

**Comment by apostiglioni** [comment]
I understand what you say about the request stream not completing because there might be more requests, but I still don't know what would be the proper way to work with the response stream.

The scenario is this: For each request, the response is a list of objects. I want to group these objects based on a property value and then reduce everything to an array of arrays, where the inner array corresponds to each of the groups.

I don't think it really matters, but just for more context, I can add that the request stream is created from scroll events in a a naive implementation of infinite scroll:

```
  const request$ = drivers.BOM.event('scroll') // <-- custom driver that listen to window.scroll events
    .filter(e => {
      const MARGIN = 50
      const scrollPos = window.pageYOffset;
      const pageHeight = document.documentElement.scrollHeight;
      const clientHeight = document.documentElement.clientHeight;

      const refresh = pageHeight - (scrollPos + clientHeight) < MARGIN;
      return refresh;
    })
    .throttle(500) // 500 just works fine
    .map(() => { return { url: HELLO_URL } })
    .startWith({ url: HELLO_URL });
...
  return {
    HTTP: request$
  }
```

**Comment by laszlokorte** [comment]
The question is why would you want the stream to complete in first place?
As @staltz suggested you probably want to use `scan` instead of `reduce` as it does not depend on the stream to complete but just accumulate the values over time and emits a new accumulated values each time a new value comes in.
