### ISSUE TITLE
please add support for: requests with responseType 'blob' and the ability to define a progress stream updated by function `xhr.progress` 

### ISSUE THREAD

**Issue by iambumblehead** [cyclejs/cycle-http-driver#46]
please add support for: responseType 'blob' and the ability to define a progress stream updated by function `xhr.progress` 

Specifically, I would like to stream this to the driver
```
{
      url: 'http://d8d913s460fub.cloudfront.net/videoserver/cat-test-video-320x240.mp4',
      crossDomain     : true,
      withCredentials : false,
      progress : progress$,
      type   : 'blob',
      method : 'GET'
}
```

`superagent` appears to have some limitations here. It does not allow one to set the contentType, supporting only 'html, json, xml and urlencoded' https://github.com/visionmedia/superagent/pull/655

**Comment by iambumblehead** [comment]
I've made this pull request to superagent which adds support for 'blob' type

https://github.com/visionmedia/superagent/pull/888

**Comment by iambumblehead** [comment]
@staltz if you would give direction for adding observable progress support I will try following with a pull request

**Comment by iambumblehead** [comment]
Adding this to http-driver updates the observer during the onprogress event when `progress` option is defined true
```javascript
if (reqOptions.progress) {
  request.on('progress', function (res) {
    res.request = reqOptions;
    observer.onNext(res);
  });
}
```

**Comment by staltz** [comment]
Thanks @iambumblehead for this suggestion. I'll most likely add support for progress, as you drafted above. Also, HTTP Driver is using an outdated version of superagent. We need to update. But also, let's see how your PR evolves on their side.

**Comment by iambumblehead** [comment]
thanks for the response I'll maintain this in a blob related branch [here][0]

[0]: https://github.com/cyclejs/cycle-http-driver/compare/master...iambumblehead:add-responsetype-support

**Comment by staltz** [comment]
@iambumblehead this is now done in v8.2.0

**Comment by iambumblehead** [comment]
@staltz thank you BUT I'm hoping you'll also add the ability to define responseType 'blob' --your v8.2.0 sources are still unable to request blob type.

related:
  https://github.com/cyclejs/cycle-http-driver/compare/master...iambumblehead:add-responsetype-support#diff-f939c6065bc0cc1eaafe84ea83760a36R34
  https://github.com/cyclejs/cycle-http-driver/compare/master...iambumblehead:add-responsetype-support#diff-f939c6065bc0cc1eaafe84ea83760a36R17

**Comment by iambumblehead** [comment]
type "json" invalidates my blob requests so additionally, I'd like the driver to require 'type' to be explicitly defined, but understand this may break dependant scripts.

related:
  https://github.com/cyclejs/cycle-http-driver/compare/master...iambumblehead:add-responsetype-support#diff-f939c6065bc0cc1eaafe84ea83760a36R30

**Comment by staltz** [comment]
You seem to already have a branch. Can you submit that as a PR?

**Comment by iambumblehead** [comment]
I'll make a PR later today after I rebase my branch
