### ISSUE TITLE
Bug (?) with server side

### ISSUE THREAD

**Issue by chadrien** [cyclejs/cycle-http-driver#47]
I'm currently having a problem with the HTTP driver, but I'm not sure if it's really a bug or just a misunderstanding from me (but I'm pretty sure it's a bug).

I have a page fetching a list of items from an HTTP request, and on the same page a button to add an item to this list via HTTP request. When I add an item to the list, I then want to refresh (re-fetch) the list so it have the new item.

I have something like this in the end (overly simplified for the issue):

```js
import { Observable } from 'rx'
import { div, button } from '@cycle/dom'

export default function main(sources) {
  const buttonClick$ = sources.DOM.select('button').events('click')
  const barLoaded$ = sources.HTTP.filter(res$ => res$.request.url === 'http://127.0.0.1:3000/bar')
    .mergeAll()

  return {
    DOM: sources.HTTP.filter(res$ => res$.request.url === 'http://127.0.0.1:3000/foo')
      .mergeAll()
      .map(res => res.body)
      .map(text => div([
        text,
        button(['click me'])
      ])),
    HTTP: Observable.merge(
      Observable.combineLatest(
        Observable.just('http://127.0.0.1:3000/foo'),
        barLoaded$.startWith(true),
        url => ({url})
      ),
      buttonClick$.map(() => ({url: 'http://127.0.0.1:3000/bar'}))
    )
  }
}
```

This works perfectly as long as I only run it on client-side.
However when I run it on server-side, the page is never loaded (infinite loading, as if trapped in an infinite loop).

I'm not sure if I'm perfectly clear, so I created a minimal application to see this error: https://github.com/chadrien/cycle-http-driver/tree/server-side-bug

So… bug, feature or misunderstanding of Rx/HTTP driver?

**Comment by laszlokorte** [comment]
there is already one basic mistake in your server code:
https://github.com/chadrien/cycle-http-driver/blob/server-side-bug/src/server.js#L23-L25
```
sources.DOM.subscribe(html => res.render('layout', {
  html
}))
```
You would not want to subscribe to the `sources.DOM` returned by `Cycle.run` but to the `sinks.DOM`.
And then you might want to only `take(1)` element.

**Comment by chadrien** [comment]
@laszlokorte you're goddamn right. How could I let this pass? duh! Obviously when subscribing to the right stuff, everything works okay ~~

Thanks for pointing this out! I guess sometimes you get too focus on something and can't see the obvious :smile:
