### ISSUE TITLE
Double-sent requests

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-http-driver#9]
```js
function main(responses) {
  console.log('This only gets called once.')
  const url = '/ontologies/acl.ttl';
  var request$ = Cycle.Rx.Observable.just(url);
  
  var vtree$ = responses.http
    .do(r => console.log('this gets called twice', r))
    .mergeAll()
    .do(r => console.log('this gets called once', r))
    .map(res => h('p', res.text.substr(0, 100) + '...'));

  return {
    dom: vtree$,
    http: request$
  };
}

let [requests, responses] = Cycle.run(main, {
  dom: makeDOMDriver('#app-container'),
  http: makeHTTPDriver(),
  db: makeLocalDbDriver(),
});
```

**Comment by tchap** [comment]
For me it looks like the request is sent 5 times :-)

**Comment by tchap** [comment]
I mean, I am sending a single GET request in my code. I am not running this particular example...

**Comment by tchap** [comment]
Actually not sure mine is the same case. I am using `mergeAll` and I am seeing everything once on the client, but the server is receiving the same request 5 times...

**Comment by tchap** [comment]
Yeah, seeing 5 responses before `mergeAll`...

**Comment by tchap** [comment]
Was trying to find the issue. Not sure why, but while `createResponse$` is called exactly once, the callback in `Rx.Observable.create` in the same function is called 5 times.

**Comment by tchap** [comment]
I mean, the create function itself is called 5 times. Totally weird...

**Comment by tchap** [comment]
Patched this lib to wrap `superagent` in a promise and then used `Rx.Observable.fromPromise` and it started working properly...

**Comment by arnodenuijl** [comment]
I think I had the same problem. One request going in to the driver and two requests being made to the server. laszlokorte explained on gitter that the function ```function createResponse$(reqOptions)``` in the driver creates a cold observable. So every subscription to the ```response$``` results in an extra call being made. Work around is to call ```share()``` on the ```response$``` you get from the driver to make the observable hot **or** to make the request ```eager``` which has the 'side' effect to make the ```response$``` hot.

If you had five requests going out then it looks like you had five effective subscriptions. I think wrapping the call in a promise has the same work around effect (making the response$ hot). 

I would expect the response$ to always be hot. Can't think of a situation where this 'cold' behavior is useful. (but maybe someone else can?!).


See http://arnodenuijl.github.io/CycleDoubleHttp/index.html for a working example where I had two calls being made off of one request. Just open the developer tools and click the button. The source code is on https://github.com/arnodenuijl/CycleDoubleHttp/blob/master/src/app.ts. In my case I used the HTTP ```response$``` for generating the ```state$``` **(line 35)**. And the ```state$``` was used for generating the ```DOM``` **(line 42)** **and** for creating the HTTP ```request$``` **(line 69)**. 

By using the ```state$``` in two places, one going into the DOM driver and one going into the HTTP driver,  two subscriptions are effective and two requests are being made.

**Comment by tchap** [comment]
@arnodenuijl Cheers, will take a look when I have time.

**Comment by laszlokorte** [comment]
@arnodenuijl Now that I think about it the reason for the observable being cold is pretty clear: If the request fails, a cold observable can retry the request just by subscribing again. With a hot observable you can not retry the request (without creating a whole new one which might not be possible if you do not know all the parameters or do not have access to the request sink or if the one finally consuming the response does not know about cycle but just consumes failable observables)

**Comment by staltz** [comment]
> I would expect the response$ to always be hot. Can't think of a situation where this 'cold' behavior is useful. (but maybe someone else can?!).

Like everything else with RxJS, cold is the default. I actually agree with you that I expect hot as default, but this is just how RxJS is, always cold by default. And there are deep implications for that. Cold is more general than Hot, so there's a reason why it's default. It's useful specially in cases where you need to retry, like Laszlo said.

So rather, than going against the RxJS normal behavior, I would stick to keeping the cold behavior, and instructing people to `.share()` those. Cycle may soon get support for multiple stream libraries, and then those may allow a hot-by-default approach.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#238
